# Generated by Django 2.1.3 on 2018-11-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='transmition',
            field=models.CharField(blank=True, default='Unknown', max_length=10),
        ),
    ]
