# Generated by Django 2.1.3 on 2018-11-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20181119_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bmw', 'BMW'), ('mercedes', 'MERCEDES BENZ'), ('toyota', 'TOYOTA'), ('honda', 'HONDA'), ('hyundai', 'HYUNDAI'), ('acura', 'ACURA'), ('nissan', 'NISSAN'), ('audi', 'AUDI'), ('mazda', 'MAZDA'), ('dodge', 'DODGE'), ('ford', 'FORD'), ('kia', 'KIA')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Moda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Make')),
            ],
        ),
        migrations.AlterField(
            model_name='cars',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Make'),
        ),
    ]
